services:
  civicvoiceserver:
    image: civicvoiceserver
    build:
      context: packages/server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
